#!/bin/bash
code --install-extension alefragnani.Bookmarks
code --install-extension amiralizadeh9480.laravel-extra-intellisense
code --install-extension bierner.markdown-mermaid
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension bpruitt-goddard.mermaid-markdown-syntax-highlighting
code --install-extension brapifra.phpserver
code --install-extension calebporzio.better-phpunit
code --install-extension christian-kohler.path-intellisense
code --install-extension codingyu.laravel-goto-view
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension emallin.phpunit
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.code-runner
code --install-extension GitHub.vscode-pull-request-github
code --install-extension glitchbl.laravel-create-view
code --install-extension golang.go
code --install-extension Gruntfuggly.todo-tree
code --install-extension Gruntfuggly.triggertaskonsave
code --install-extension hbenl.vscode-test-explorer
code --install-extension humao.rest-client
code --install-extension ICS.japanese-proofreading
code --install-extension IHunte.laravel-blade-wrapper
code --install-extension ikappas.phpcs
code --install-extension junstyle.php-cs-fixer
code --install-extension liximomo.sftp
code --install-extension mechatroner.rainbow-csv
code --install-extension MehediDracula.php-namespace-resolver
code --install-extension mhutchie.git-graph
code --install-extension mikestead.dotenv
code --install-extension mitchdenny.ecdc
code --install-extension mosapride.zenkaku
code --install-extension ms-azuretools.vscode-docker
code --install-extension MS-CEINTL.vscode-language-pack-ja
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vscode.test-adapter-converter
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension naoray.laravel-goto-components
code --install-extension nickdemayo.vscode-json-editor
code --install-extension oderwat.indent-rainbow
code --install-extension onecentlin.laravel-blade
code --install-extension onecentlin.laravel-extension-pack
code --install-extension onecentlin.laravel5-snippets
code --install-extension rebornix.ruby
code --install-extension recca0120.vscode-phpunit
code --install-extension redhat.java
code --install-extension ritwickdey.live-sass
code --install-extension ritwickdey.LiveServer
code --install-extension robberphex.php-debug
code --install-extension ryannaddy.laravel-artisan
code --install-extension ryu1kn.partial-diff
code --install-extension sachittandukar.laravel-5-snippets
code --install-extension saikou9901.evilinspector
code --install-extension shardulm94.trailing-spaces
code --install-extension shufo.vscode-blade-formatter
code --install-extension stef-k.laravel-goto-controller
code --install-extension stylelint.vscode-stylelint
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wingrunr21.vscode-ruby
code --install-extension withfig.fig
code --install-extension wix.vscode-import-cost
code --install-extension wordpresstoolbox.wordpress-toolbox
code --install-extension xdebug.php-debug
code --install-extension yzane.markdown-pdf
